name: run-tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup
        uses: actions/checkout@v3
      - name: Setup java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
      #  run: mvn -B package --file pom.xml
        run: mvn --batch-mode -DskipTests package
      - name: Run tests
        run: mvn --batch-mode test